/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:df6d2e0a-c800-4688-8d64-565dbb151f47",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_KhTRtCdAg",
    "aws_user_pools_web_client_id": "1dqocojlpbgii6qbjcrdadnhtd",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://jow435bxv5akra3gqre6oxu6dy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-zk73vr7pzbcvzfedpecgwyou2q",
    "aws_user_files_s3_bucket": "launcher618ae131b5a24e17b9617e453ad6b3a5181606-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
